### ISSUE TITLE
release for 2.12 pls?

### ISSUE THREAD

**Issue by neko-kai** [drivetribe/circe-field-hints#1]
Preferrably on maven central

**Comment by joan38** [comment]
Hi @kaishh I will do that.
We just created your com.drivetribe repo on Maven Central.

**Comment by neko-kai** [comment]
@joan38 Thank you!

**Comment by joan38** [comment]
@kaishh The version 0.3 will be on Maven Central in the next 2h.
Note that dependency is now: `"com.drivetribe" %% "circe-field-hints" % "0.3"`
`com.drivetribe` instead of `io.chumps`.

**Comment by joan38** [comment]
I made a mistake so it will be on `0.4`
